### ISSUE TITLE
cluster status: down ... eventhough there is one (single-node) ES running locally

### ISSUE THREAD

**Issue by Analect** [DigElements/elastic-client#1]
I was delighted to see some elasticsearch elements emerge for polymer .. but can't seem to get this basic one to acknowledge a connection.
I have tried all sorts of variations of enabling 'cors' in the elasticsearch.yml ... and have tried on various ES versions 1.4.4, 1.75, 2.2 etc.. all without joy. In all cases, the elasticsearch installations happen to be in a docker container ... but they expose their port 9200 back to the host.

Should this basic demo page acknowledge a local ES installation.  I have all the dependency packages in the same /bower_components/ folder. Thanks.

![image](https://cloud.githubusercontent.com/assets/4063815/14540582/b11132b2-027d-11e6-8fdc-2b7f410b35f6.png)

**Comment by Analect** [comment]
Closing this out ... if I'm running this locally ... will just have to point at a non local ES instance .. seems to be the only way around this CORS issue.

**Comment by ghost** [comment]
Sorry I cannot answer your question until next week. Make sure that your
elastic server is configured to allow CORS if you are connecting to a
remote server.

**Comment by ghost** [comment]
Oops, just read your report that you did enable CORS.

**Comment by Analect** [comment]
@flyntde 
Thanks for coming back to me, but don't worry about a response ref above. I was able to get the this (in fact the elastic-client-search element) working by modifying 'localhost' in the demo to another machine, which has skirted around the CORS related issue, that I can't seem to figure out. Using polyserve, as per the readme there, got around the need to adjust references to dependencies in a bower_components directory.
Separately, I was following along the dig-polymer work, but I think the mapping structure and demo data for `mockads` has changed from what's in the data folders of some elements. It would be great to get that realigned. Thanks again for your efforts.

**Comment by ghost** [comment]
<blockquote>
Separately, I was following along the dig-polymer work, but I think the mapping structure and demo data for mockads has changed from what's in the data folders of some elements. It would be great to get that realigned. Thanks again for your efforts.
</blockquote>

@Analect 
Thanks for the feedback.  We will get a better demo application under DigElements to demonstrate each published component -- when we can.  We are developing the elastic Polymer elements and using them in the dig-polymer application which is specific to some real crawled data.  We hope to provide at least as much functionality as [ElasticUI ](https://github.com/YousefED/ElasticUI) and [searchkit](http://www.searchkit.co), and then also address multiple types with filters and aggregation.  It is going to take a while because there are just two of us, and much time is split between developing our applications that use the elastic elements and the elastic elements.  Lots of work, but we are learning and getting there little by little.

**Comment by Analect** [comment]
@flyntde 
Thanks for the colour. Yes, I'm aware of both elasticui and searchkit and therefore interested in how you are tackling it in polymer. There's a group at nuxeo doing some interesting work too.  For instance, look [here](http://nuxeo.github.io/nuxeo-web-ui/#!/search)  and [here](https://github.com/nuxeo/nuxeo-dataviz-elements/blob/master/nuxeo-es-search.html). The former link appears to sit on top of an RDBMS data-source, from what I can tell (I could be wrong), although I know they have some ES in the mix, as per the second link. Their approach may be informative for you ... or not, as the case may be.

I would like to be able to track the progress at [dig-polymer](https://github.com/NextCenturyCorporation/dig-polymer) a bit more closely, but as mentioned above, it requires for that repo to point at an ES instance where the data is aligned ... a bit like how you give sample data in some of your elements. I know the data model may be changing alot, but to the extent you could add a script into the data folder of dig-polymer to get things realigned, that would be really great, so that I can reproduce the dummy ES instance on which that repo works against.

Thanks for your efforts.
